version: 2.1

orbs:
  node: circleci/node@4.3.0

jobs:
  test:
    executor:
      name: node/default
      tag: <<parameters.version>>
    parameters:
      version:
        type: string
      gawk:
        type: string
        default: gawk-5.1.0
    steps:
      - checkout
      - run: wget https://ftp.gnu.org/gnu/gawk/<<parameters.gawk>>.tar.gz
      - run: tar -xvpzf <<parameters.gawk>>.tar.gz
      - run: cd <<parameters.gawk>> && ./configure && make
      - run: npm install
      - run: PATH=$PATH:<<parameters.gawk>> npm test

workflows:
  test:
    jobs:
      - test:
          version: 10.14.2
      - test:
          version: 12.0.0
      - test:
          version: 14.0.0
      - test:
          version: 16.0.0
