version: 2.1

orbs:
  node: circleci/node@6.3.0

workflows:
  test:
    jobs:
      - node/test:
          setup:
            - run: wget https://ftp.gnu.org/gnu/gawk/gawk-5.1.0.tar.gz
            - run: tar -xvpzf gawk-5.1.0.tar.gz
            - run: cd gawk-5.1.0 && ./configure && make
            - run: echo 'export PATH="$PATH:gawk-5.1.0"' >>"$BASH_ENV"
            # derive cache key from package.json
            - run: cp package.json package-lock.json
          override-ci-command: rm package-lock.json && npm install && git checkout -- package.json
          matrix:
            parameters:
              version:
                - 18.0.0
                - 20.0.0
                - 22.0.0
